swagger-api:
  version: "1.0"


server:
  port: 2000
  servlet:
    context-path: /Library

spring:
  jpa:
    database: postgresql
    open-in-view: true
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Library
    username: postgres
    password: root


logging:
  level:
    web: debug


management:
  endpoints:
    web:
      exposure:
        include: health,info


spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
